config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#top'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image

  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)#bookから@bookに変更
    if @book.save#bookから@bookに変更
    redirect_to book_path(@book.id), notice: 'Thank you,successfully created!'
   #↑bookから@bookに変更
    else
      @books = Book.all#インスタンス変数追加
      render :index #booksをindexに変更#indexのviewページへ
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    #インスタンス変数@bookを追加

  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books', notice: 'successfully destroyed.'
  end

  def update
    @book = Book.find(params[:id])#title,body,errorの情報が含まれる
    if @book.update(book_params)
    redirect_to book_path(@book.id), notice: 'Thank you,successfully updated!'
    else
      render :edit
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end
#.require(:book)いらない？
#require(対象).permit(対象の名前、タイトルなど)

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %>errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @book, url: book_path(@book.id) do |f| %>

<h4>本のタイトル</h4>
<%= f.text_field :title %>

<h4>感想</h4>
<%= f.text_area :body %>

<p>
<%= f.submit 'Update Book' %>
</p>

<%=link_to "Show",book_path(@book.id) %>
|
<%=link_to "Back",books_path %>
<% end %>

app/views/books/index.html.erb
<p id="notice">
  <%= notice %>
</p>


<h1>Books</h1>




<table>
   <tr>
      <th>本のタイトル</th>
      <th>感想</th>
      <th colspan="3"></th>
    </tr>
<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>

    <td>
    <%=link_to "Show",book_path(book.id) %>
    </td>

    <td>
　　<%=link_to "Edit",edit_book_path(book.id) %>
    </td>
    <td>
    <%= link_to "Destroy", book_path(book.id), method: :delete,"data-confirm" => "Are you sure?" %>
    </td>

  </tr>
<% end %>
 </table>





<h2>New book</h2>
<div id="error_explanation">
<% #@booksから@bookに変更　%>
<% if @book.errors.any? %>
  <h2>
   <%= @book.errors.count %>errors prohibited this book from being saved:
  </h2>

  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>

<% end %>
</div>


<%= form_with model: @book do |f| %>
<h4>本のタイトル</h4>
<%= f.text_field :title %>

<h4>感想</h4>
<%= f.text_area :body %>

<%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with model: @book do |f| %>
<h4>本のタイトル</h4>
<%= f.text_field :title %>

<h4>感想</h4>
<%= f.text_area :body %>

<%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<p id="notice">
  <%= notice %>
</p>

<p>
  <strong>本のタイトル：</strong>
  <%= @book.title %>
</p>

<p>
  <strong>感想：</strong>
  <%= @book.body %>
</p>

<%=link_to "Edit",edit_book_path(@book.id) %>
|
<%=link_to "Back",books_path %>

app/views/homes/top.html.erb
<body>
<h1>
  ようこそ 
  <strong>Bookers</strong>
   へ!
</h1>

  <p>
　   <strong>Bookers</strong>
　   では、さまざまな書籍に関するあなたの意見や
  </p>
  
  <p>
　   印象を共有し交換することができます
  </p>

  <p>
　   <a href="/books">start</a>
  </p>


</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>